openapi: 3.0.0
info:
    title: Posts Platform API
    version: 1.0.0
    description: API for user management

paths:
    /auth/sign-in:
        post:
            summary: Authorize user
            tags: [Auth]
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                password:
                                    type: string
                                email:
                                    type: string
            responses:
                201:
                    description: User was authorized successfully
                500:
                    description: Internal server error

    /api/posts:
        get:
            summary: Get all posts
            tags: [Posts]
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        id:
                                            type: integer
                                        message:
                                            type: string
                                        userId:
                                            type: integer
                                        createdAt:
                                            type: string
                                            format: date-time
                                        updatedAt:
                                            type: string
                                            format: date-time
                500:
                    description: Internal server error
