FROM node:lts

WORKDIR /app

COPY ./src ./src
COPY ./prisma ./prisma
COPY ./.env.docker ./.env
COPY ./package.json ./tsconfig.json ./

RUN npm install -g typescript
RUN npm install
RUN tsc
RUN rm -rf ./src
RUN mv ./dist/src ./
RUN rm -rf ./dist

EXPOSE 3000
